### ISSUE TITLE
More aggressive optimizations

### ISSUE THREAD

**Issue by alyssarosenzweig** [TitanCast/JavaScript-API#1]

**Comment by amishshah** [comment]
Could you elaborate? Thanks

**Comment by alyssarosenzweig** [comment]
@hydrabolt The minified output is clearly optimized, but it's much more verbose than it really should be...

**Comment by amishshah** [comment]
Ah ok @bobbybee, thanks, will change it

**Comment by amishshah** [comment]
Sorry it took so long @bobbybee! Can you check if the new commit makes the API less verbose? I removed useless getter and setter functions.
